# Generated by Django 4.2.1 on 2023-05-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
